name: top2cche1d
channels:
  - conda-forge
  - plotly
dependencies:
  - python==3.9.1
  - ipykernel
  - numpy==1.21.5
  - pandas==1.4.2
  - plotly_express==0.4.1
  - nbformat==5.3.0
  - gdal==3.4.1
  - affine==2.3.0
